 
 /*------------------------------------------------------------------------
    File        : Order_Push
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : AKulanda
    Created     : Fri Nov 23 16:31:00 EST 2018
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS Order_Push: 

END CLASS.